# Generated by Django 2.1.7 on 2019-03-13 08:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('canonapp', '0006_auto_20190306_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesReportArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2019, 3, 13, 8, 6, 27, 686979, tzinfo=utc))),
                ('Name', models.CharField(default='Name', max_length=100, null=True)),
                ('Amount', models.FloatField(default=0.0, null=True)),
                ('Reason', models.CharField(max_length=100, null=True)),
                ('ReceivedBy', models.CharField(default='Name', max_length=100)),
                ('ApprovedBy', models.CharField(default='Name', max_length=100)),
                ('month', models.CharField(max_length=100, null=True)),
                ('year', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryReportArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2019, 3, 13, 8, 6, 27, 687966, tzinfo=utc))),
                ('Salary_Type', models.CharField(max_length=100, null=True)),
                ('Staff', models.CharField(max_length=100, null=True)),
                ('Month', models.CharField(max_length=100, null=True)),
                ('Amount', models.IntegerField(default=0)),
                ('archivedmonth', models.CharField(max_length=100, null=True)),
                ('archivedyear', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SundryReportArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2019, 3, 13, 8, 6, 27, 687446, tzinfo=utc))),
                ('Name', models.CharField(default='Name', max_length=100, null=True)),
                ('Amount', models.FloatField(default=0.0, null=True)),
                ('Reason', models.CharField(max_length=100, null=True)),
                ('ReceivedBy', models.CharField(default='Name', max_length=100)),
                ('ApprovedBy', models.CharField(default='Name', max_length=100)),
                ('month', models.CharField(max_length=100, null=True)),
                ('year', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='complaints',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 13, 8, 6, 27, 682375, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver_checklist',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 13, 8, 6, 27, 684760, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver_payment_report',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 13, 8, 6, 27, 683414, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver_payment_reports_archive',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 13, 8, 6, 27, 684319, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driverpayment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 13, 8, 6, 27, 682953, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driverpayments_archive',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 13, 8, 6, 27, 683809, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 13, 8, 6, 27, 685654, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 13, 8, 6, 27, 686537, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 13, 8, 6, 27, 686151, tzinfo=utc)),
        ),
    ]
