# Generated by Django 2.1.7 on 2019-03-25 07:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('canonapp', '0009_auto_20190313_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 7, 20, 51, 503500, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver_checklist',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 7, 20, 51, 505805, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver_payment_report',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 7, 20, 51, 504453, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver_payment_reports_archive',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 7, 20, 51, 505368, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driverpayment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 7, 20, 51, 504001, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driverpayments_archive',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 7, 20, 51, 504863, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expensesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 7, 20, 51, 507553, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 7, 20, 51, 506261, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Salary_Type',
            field=models.CharField(choices=[('ALLOWANCE', 'Pay Allowances'), ('Salary', 'Monthly Salary'), ('Advance', 'Pay Advances'), ('Commission', 'Pay Commission')], default='Choose Salary Type', max_length=12),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.Staff'),
        ),
        migrations.AlterField(
            model_name='salaryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 7, 20, 51, 508536, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='ApprovedBy',
            field=models.CharField(default='Manager-Patrick', max_length=100),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 7, 20, 51, 507132, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='PaymentMadeTo',
            field=models.CharField(default='Type Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='spend',
            name='ReasonForPayment',
            field=models.TextField(default='Type Main Expense', max_length=100),
        ),
        migrations.AlterField(
            model_name='spend',
            name='ReceivedBy',
            field=models.CharField(default='Accountant-Nelvin', max_length=100),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 7, 20, 51, 506738, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='PaymentMadeTo',
            field=models.CharField(default='Type Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='sundryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 7, 20, 51, 508020, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='StaffDetails',
        ),
    ]
