# Generated by Django 2.1.7 on 2019-03-25 07:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('canonapp', '0010_auto_20190325_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 7, 32, 24, 713485, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver_checklist',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 7, 32, 24, 715902, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver_payment_report',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 7, 32, 24, 714484, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver_payment_reports_archive',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 7, 32, 24, 715418, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driverpayment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 7, 32, 24, 714022, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driverpayments_archive',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 7, 32, 24, 714887, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expensesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 7, 32, 24, 718156, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='AmountInWords',
            field=models.CharField(default='amount in words', max_length=1000),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 7, 32, 24, 716672, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salaryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 7, 32, 24, 719233, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 7, 32, 24, 717709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='ReasonForPayment',
            field=models.CharField(default='Type Main Expense', max_length=1000),
        ),
        migrations.AlterField(
            model_name='spend',
            name='ReceivedBy',
            field=models.CharField(default='Person Receiving Money', max_length=100),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='AmountInWords',
            field=models.CharField(default='amount in words', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 7, 32, 24, 717264, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='ReasonForPayment',
            field=models.CharField(default='Only relatively small expense', max_length=500),
        ),
        migrations.AlterField(
            model_name='sundryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 25, 7, 32, 24, 718645, tzinfo=utc)),
        ),
    ]
