# Generated by Django 2.1.7 on 2019-03-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190228_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('dob', models.DateTimeField(verbose_name='Birth Date')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.IntegerField(default='+256701345376')),
                ('role', models.CharField(choices=[('Others', 'Others'), ('Executive', 'Executive'), ('Manager', 'Manager'), ('Receptionist', 'Receptionist'), ('Accountant', 'Accountant'), ('Operations', 'Operations')], default='', max_length=20)),
                ('duties', models.TextField(max_length=200)),
                ('salary', models.IntegerField(default='300000')),
            ],
        ),
    ]
