# Generated by Django 2.1.7 on 2019-03-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='dob',
            field=models.DateField(verbose_name='Birth Date'),
        ),
    ]
